function labelForFallback(fallback) {
  return fallback ? "Fixture fallback" : "Live generation";
}

function labelForLora(status) {
  const lora = status?.lora;
  if (lora === "active") return "LoRA active";
  if (lora === "pending") return "LoRA pending";
  return "LoRA none";
}

export default function FalPanel({ creature, spriteStatus }) {
  const status = spriteStatus || creature?.providerStatus || {};
  const fallback = Boolean(spriteStatus?.fallback ?? creature?.fallback);
  const latencyMs = spriteStatus?.latencyMs ?? creature?.latencyMs;
  const provider = status.provider || "fal";
  const model = status.modelId || "pending";

  return (
    <aside className="fal-panel" aria-label="fal generation status">
      <div className="fal-panel__head">
        <span>fal</span>
        <strong>{labelForFallback(fallback)}</strong>
      </div>
      <dl className="fal-panel__grid">
        <div>
          <dt>Provider</dt>
          <dd>{provider}</dd>
        </div>
        <div>
          <dt>Model</dt>
          <dd>{model}</dd>
        </div>
        <div>
          <dt>LoRA</dt>
          <dd>{labelForLora(status)}</dd>
        </div>
        <div>
          <dt>Latency</dt>
          <dd>{typeof latencyMs === "number" ? `${latencyMs}ms` : "pending"}</dd>
        </div>
      </dl>
      <p className="fal-panel__note">
        {fallback ? "Using deterministic arena visual metadata." : "Generated by fal from the creature prompt."}
      </p>
    </aside>
  );
}
